add commit sha to jar

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,17 +7,38 @@ jobs:
     steps:
       - name: checkout repository
         uses: actions/checkout@v4
+
       - name: validate gradle wrapper
         uses: gradle/actions/wrapper-validation@v4
+
       - name: setup jdk
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'microsoft'
+
       - name: make gradle wrapper executable
         run: chmod +x ./gradlew
+
       - name: build
         run: ./gradlew build
+
+      - name: get short commit sha
+        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+
+      - name: rename jar with commit id
+        run: |
+          SHORT_SHA=${{ env.SHORT_SHA }}
+          JAR_BASENAME=chunkaddons-1.0.0
+          ORIGINAL_JAR="build/libs/${JAR_BASENAME}.jar"
+          RENAMED_JAR="build/libs/${JAR_BASENAME}-${SHORT_SHA}.jar"
+          if [ -f "$ORIGINAL_JAR" ]; then
+            mv "$ORIGINAL_JAR" "$RENAMED_JAR"
+          else
+            echo "Jar not found: $ORIGINAL_JAR"
+            exit 1
+          fi
+
       - name: capture build artifacts
         uses: actions/upload-artifact@v4
         with:
